// Package main генерирует методы Reset для помеченных struct'ов.
// Ищет корень модуля (go.mod), парсит исходники и пишет reset.gen.go.
// Сгенерированные Reset зануляют поля и безопасно вызывают Reset у вложенных типов.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root, err := findProjectRoot()
	if err != nil {
		panic(err)
	}

	pkgs, err := scanPackages(root)
	if err != nil {
		panic(err)
	}

	for _, pkg := range pkgs {
		var generated []string

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok || gen.Tok != token.TYPE {
					continue
				}

				if !hasResetComment(gen.Doc) {
					continue
				}

				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					method := generateResetMethod(ts.Name.Name, st)
					generated = append(generated, method)
				}
			}
		}

		if len(generated) == 0 {
			continue
		}

		err := writeResetFile(pkg, generated)
		if err != nil {
			panic(err)
		}
	}
}

func writeResetFile(pkg *PackageInfo, methods []string) error {
	var b bytes.Buffer

	b.WriteString("// Code generated by reset; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg.Name + "\n\n")

	for _, m := range methods {
		b.WriteString(m)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile(
		filepath.Join(pkg.Dir, "reset.gen.go"),
		src,
		0644,
	)
}

func hasResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(c.Text) == "// generate:reset" {
			return true
		}
	}
	return false
}

func generateResetMethod(structName string, st *ast.StructType) string {
	var b strings.Builder

	fmt.Fprintf(&b, "func (rs *%s) Reset() {\n", structName)
	fmt.Fprintf(&b, "\tif rs == nil {\n\t\treturn\n\t}\n\n")

	for _, field := range st.Fields.List {
		// embedded-поля пропускаем
		if len(field.Names) == 0 {
			continue
		}

		for _, name := range field.Names {
			b.WriteString(generateFieldReset("rs."+name.Name, field.Type))
		}
	}

	b.WriteString("}\n\n")
	return b.String()
}

func generateFieldReset(expr string, t ast.Expr) string {
	switch tt := t.(type) {

	case *ast.Ident:
		if isPrimitive(tt.Name) {
			return fmt.Sprintf("\t%s = %s\n", expr, zeroValue(tt.Name))
		}

		// пользовательский тип → пробуем Reset()
		return generateResetCall(expr)

	case *ast.ArrayType:
		if tt.Len == nil {
			return fmt.Sprintf("\t%s = %s[:0]\n", expr, expr)
		}

	case *ast.MapType:
		return fmt.Sprintf("\tclear(%s)\n", expr)

	case *ast.StarExpr:
		return generatePointerReset(expr, tt.X)

	case *ast.SelectorExpr:
		// pkg.Type → тоже пользовательский тип
		return generateResetCall(expr)
	}

	return ""
}

func isPrimitive(t string) bool {
	switch t {
	case
		"bool",
		"string",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return true
	default:
		return false
	}
}

func generatePointerReset(ptr string, elem ast.Expr) string {
	var b strings.Builder

	fmt.Fprintf(&b, "\tif %s != nil {\n", ptr)

	switch elem.(type) {

	// указатель на примитив
	case *ast.Ident:
		fmt.Fprintf(&b, "\t\t*%s = %s\n", ptr, zeroValue(exprName(elem)))

	// указатель на slice / map / struct
	default:
		b.WriteString(indent(generateFieldReset("*"+ptr, elem), 2))
	}

	fmt.Fprintf(&b, "\t}\n")
	return b.String()
}

func generateResetCall(expr string) string {
	return fmt.Sprintf(
		"\tif r, ok := any(%s).(interface{ Reset() }); ok {\n\t\tr.Reset()\n\t}\n",
		expr,
	)
}

func zeroValue(t string) string {
	switch t {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "float32", "float64":
		return "0.0"
	default:
		return "0"
	}
}

func exprName(e ast.Expr) string {
	if id, ok := e.(*ast.Ident); ok {
		return id.Name
	}
	return ""
}

func indent(s string, tabs int) string {
	prefix := strings.Repeat("\t", tabs)
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i := range lines {
		lines[i] = prefix + strings.TrimLeft(lines[i], "\t")
	}
	return strings.Join(lines, "\n") + "\n"
}

// PackageInfo содержит информацию о пакете
type PackageInfo struct {
	Name  string
	Dir   string
	Files []*ast.File
	Fset  *token.FileSet
}

var skipDirs = map[string]struct{}{
	".github":    {},
	".git":       {},
	".vscode":    {},
	"api":        {},
	"cmd":        {},
	"migrations": {},
}

func scanPackages(root string) (map[string]*PackageInfo, error) {
	packages := make(map[string]*PackageInfo)

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, _ error) error {
		// Пропускаем ненужные директории
		if d.IsDir() {
			base := filepath.Base(path)
			if _, ok := skipDirs[base]; ok {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(
			fset,
			path,
			nil,
			parser.ParseComments,
		)
		if err != nil {
			return err
		}

		dir := filepath.Dir(path)
		pkgKey := dir + ":" + file.Name.Name

		pkg, ok := packages[pkgKey]
		if !ok {
			pkg = &PackageInfo{
				Name: file.Name.Name,
				Dir:  dir,
				Fset: fset,
			}
			packages[pkgKey] = pkg
		}

		pkg.Files = append(pkg.Files, file)
		return nil
	})

	if err != nil {
		return nil, err
	}

	return packages, nil
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}

		dir = parent
	}
}
