// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	audit "github.com/Skifskii/link-shortener/internal/service/audit"
	mock "github.com/stretchr/testify/mock"
)

// AuditEventNotifier is an autogenerated mock type for the AuditEventNotifier type
type AuditEventNotifier struct {
	mock.Mock
}

// NotifyAll provides a mock function with given fields: _a0
func (_m *AuditEventNotifier) NotifyAll(_a0 *audit.Event) {
	_m.Called(_a0)
}

// NewAuditEventNotifier creates a new instance of AuditEventNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventNotifier {
	mock := &AuditEventNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
