// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Shortener is an autogenerated mock type for the Shortener type
type Shortener struct {
	mock.Mock
}

// Shorten provides a mock function with given fields: userID, longURL
func (_m *Shortener) Shorten(userID int, longURL string) (string, error) {
	ret := _m.Called(userID, longURL)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, string) (string, error)); ok {
		return rf(userID, longURL)
	}
	if rf, ok := ret.Get(0).(func(int, string) string); ok {
		r0 = rf(userID, longURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = rf(userID, longURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShortener creates a new instance of Shortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Shortener {
	mock := &Shortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
